package ui;

import connectDB.ConnectDB;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * @author nvmin Default Color : [0,102,51] Clicked Color : [255,255,255]
 */
public class Dashboard_GUI extends javax.swing.JFrame {

    public String currentUser = "fail";

    Calendar calendar;
    SimpleDateFormat timeFormat;
    SimpleDateFormat dayFormat;
    SimpleDateFormat dateFormat;
    String time;
    String day;
    String date;

    Color defaultColor, clickedColor;

    public Dashboard_GUI() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        defaultColor = new Color(0, 102, 51);
        clickedColor = new Color(0, 54, 27);

        //
        timeFormat = new SimpleDateFormat("HH:mm:ss");
        dayFormat = new SimpleDateFormat("EEEE");
        dateFormat = new SimpleDateFormat("MMMMM dd, yyyy");

        setTime();
    }

    public void setTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                time = timeFormat.format(Calendar.getInstance().getTime());
                timeLabel.setText(time);

                day = dayFormat.format(Calendar.getInstance().getTime());
                dayLabel.setText(day + ",");

                date = dateFormat.format(Calendar.getInstance().getTime());
                dateLabel.setText(date);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_menu_name = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dayLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_nameShop = new javax.swing.JLabel();
        jPanel_menu = new javax.swing.JPanel();
        jPanel_menu_1 = new javax.swing.JPanel();
        jLabel_menu_1_icon = new javax.swing.JLabel();
        jLabel_menu_1_text = new javax.swing.JLabel();
        jPanel_menu_2 = new javax.swing.JPanel();
        jLabel_menu_2_icon = new javax.swing.JLabel();
        jLabel_menu_2_text = new javax.swing.JLabel();
        jPanel_menu_3 = new javax.swing.JPanel();
        jLabel_menu_3_icon = new javax.swing.JLabel();
        jLabel_menu_3_text = new javax.swing.JLabel();
        jPanel_menu_4 = new javax.swing.JPanel();
        jLabel_menu_4_icon = new javax.swing.JLabel();
        jLabel_menu_4_text = new javax.swing.JLabel();
        jPanel_menu_5 = new javax.swing.JPanel();
        jLabel_menu_5_icon = new javax.swing.JLabel();
        jLabel_menu_5_text = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_user = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jDesktopPane_main = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setUndecorated(true);
        setResizable(false);

        jPanel_header.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_header.setPreferredSize(new java.awt.Dimension(873, 100));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel_menu_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        jLabel_close.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));

        dayLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        dayLabel.setForeground(new java.awt.Color(255, 255, 255));
        dayLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(dayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_menu_name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_menu_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-logo-72.png"))); // NOI18N

        jLabel_nameShop.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel_nameShop.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nameShop.setText("Eleven Coffee");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_nameShop, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nameShop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_header, java.awt.BorderLayout.PAGE_START);

        jPanel_menu.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(200, 534));

        jPanel_menu_1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_menu_1.setFocusable(false);
        jPanel_menu_1.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel_menu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_1MouseClicked(evt);
            }
        });

        jLabel_menu_1_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu_1_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/store.png"))); // NOI18N

        jLabel_menu_1_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_1_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_1_text.setText("Tại bàn");

        javax.swing.GroupLayout jPanel_menu_1Layout = new javax.swing.GroupLayout(jPanel_menu_1);
        jPanel_menu_1.setLayout(jPanel_menu_1Layout);
        jPanel_menu_1Layout.setHorizontalGroup(
            jPanel_menu_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_1Layout.createSequentialGroup()
                .addComponent(jLabel_menu_1_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_menu_1_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_menu_1Layout.setVerticalGroup(
            jPanel_menu_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_menu_1_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel_menu_1_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_menu_2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_menu_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_menu_2.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel_menu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_2MouseClicked(evt);
            }
        });

        jLabel_menu_2_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu_2_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag.png"))); // NOI18N

        jLabel_menu_2_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_2_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_2_text.setText("Tại quầy");

        javax.swing.GroupLayout jPanel_menu_2Layout = new javax.swing.GroupLayout(jPanel_menu_2);
        jPanel_menu_2.setLayout(jPanel_menu_2Layout);
        jPanel_menu_2Layout.setHorizontalGroup(
            jPanel_menu_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_2Layout.createSequentialGroup()
                .addComponent(jLabel_menu_2_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_menu_2_text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanel_menu_2Layout.setVerticalGroup(
            jPanel_menu_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_menu_2_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel_menu_2_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_menu_3.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_menu_3.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel_menu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_3MouseClicked(evt);
            }
        });

        jLabel_menu_3_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu_3_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pie-chart.png"))); // NOI18N

        jLabel_menu_3_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_3_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_3_text.setText("Báo cáo");

        javax.swing.GroupLayout jPanel_menu_3Layout = new javax.swing.GroupLayout(jPanel_menu_3);
        jPanel_menu_3.setLayout(jPanel_menu_3Layout);
        jPanel_menu_3Layout.setHorizontalGroup(
            jPanel_menu_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_3Layout.createSequentialGroup()
                .addComponent(jLabel_menu_3_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_menu_3_text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanel_menu_3Layout.setVerticalGroup(
            jPanel_menu_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_menu_3_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel_menu_3_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_menu_4.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_menu_4.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel_menu_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_4MouseClicked(evt);
            }
        });

        jLabel_menu_4_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu_4_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/users-round.png"))); // NOI18N

        jLabel_menu_4_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_4_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_4_text.setText("Khách hàng");

        javax.swing.GroupLayout jPanel_menu_4Layout = new javax.swing.GroupLayout(jPanel_menu_4);
        jPanel_menu_4.setLayout(jPanel_menu_4Layout);
        jPanel_menu_4Layout.setHorizontalGroup(
            jPanel_menu_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_4Layout.createSequentialGroup()
                .addComponent(jLabel_menu_4_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_menu_4_text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanel_menu_4Layout.setVerticalGroup(
            jPanel_menu_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_menu_4_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addComponent(jLabel_menu_4_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_menu_5.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_menu_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_menu_5.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel_menu_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_5MouseClicked(evt);
            }
        });

        jLabel_menu_5_icon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_menu_5_icon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_5_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu_5_icon.setText("...");

        jLabel_menu_5_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu_5_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu_5_text.setText("Quản lý");

        javax.swing.GroupLayout jPanel_menu_5Layout = new javax.swing.GroupLayout(jPanel_menu_5);
        jPanel_menu_5.setLayout(jPanel_menu_5Layout);
        jPanel_menu_5Layout.setHorizontalGroup(
            jPanel_menu_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_5Layout.createSequentialGroup()
                .addComponent(jLabel_menu_5_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_menu_5_text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );
        jPanel_menu_5Layout.setVerticalGroup(
            jPanel_menu_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_menu_5_text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addGroup(jPanel_menu_5Layout.createSequentialGroup()
                .addComponent(jLabel_menu_5_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_user, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_menu_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_menu_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_menu_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_menu_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_menu_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addComponent(jPanel_menu_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_menu_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_menu_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_menu_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_menu_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_menu, java.awt.BorderLayout.LINE_START);

        jDesktopPane_main.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhóm 11 : Quản lý bán hàng tại 1 quán coffee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jDesktopPane_main.add(jPanel1);

        getContentPane().add(jDesktopPane_main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked
//open menu 1
    private void jPanel_menu_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_1MouseClicked
        jPanel_menu_1.setBackground(clickedColor);
        jPanel_menu_2.setBackground(defaultColor);
        jPanel_menu_3.setBackground(defaultColor);
        jPanel_menu_4.setBackground(defaultColor);
        jPanel_menu_5.setBackground(defaultColor);
        jLabel_menu_name.setIcon(null);
        jLabel_menu_name.setText("Tại cửa hàng");
        jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-user-round-32.png")));
        jLabel_user.setText(currentUser);
        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-40.png")));
        Menu_1_TaiBan_Internal_GUI menu_1 = new Menu_1_TaiBan_Internal_GUI();
        menu_1.jLabel_currentUS.setText(jLabel_user.getText());

        jDesktopPane_main.removeAll();
        jDesktopPane_main.add(menu_1).setVisible(true);

        menu_1.setSize(jDesktopPane_main.getSize());

        jDesktopPane_main.revalidate();
        jDesktopPane_main.repaint();
    }//GEN-LAST:event_jPanel_menu_1MouseClicked

//open menu 3
    private void jPanel_menu_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_3MouseClicked
        jPanel_menu_1.setBackground(defaultColor);
        jPanel_menu_2.setBackground(defaultColor);
        jPanel_menu_3.setBackground(clickedColor);
        jPanel_menu_4.setBackground(defaultColor);
        jPanel_menu_5.setBackground(defaultColor);
        jLabel_menu_name.setIcon(null);
        jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-user-round-32.png")));
        jLabel_menu_name.setText("Tổng quan");
        jLabel_user.setText(currentUser);
        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-40.png")));

        Menu_3__ThongKe_Internal_GUI menu_3 = new Menu_3__ThongKe_Internal_GUI();
        jDesktopPane_main.removeAll();
        jDesktopPane_main.add(menu_3).setVisible(true);

        menu_3.setSize(jDesktopPane_main.getSize());

        jDesktopPane_main.revalidate();
        jDesktopPane_main.repaint();
    }//GEN-LAST:event_jPanel_menu_3MouseClicked
//open menu 4
    private void jPanel_menu_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_4MouseClicked
        jPanel_menu_1.setBackground(defaultColor);
        jPanel_menu_2.setBackground(defaultColor);
        jPanel_menu_3.setBackground(defaultColor);
        jPanel_menu_4.setBackground(clickedColor);
        jPanel_menu_5.setBackground(defaultColor);
        jLabel_menu_name.setIcon(null);
        jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-user-round-32.png")));
        jLabel_menu_name.setText("Khách hàng thành viên");
        jLabel_user.setText(currentUser);
        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-40.png")));

        Menu_4_KhachHang_Internal_GUI menu_4 = new Menu_4_KhachHang_Internal_GUI();
        jDesktopPane_main.removeAll();
        jDesktopPane_main.add(menu_4).setVisible(true);

        menu_4.setSize(jDesktopPane_main.getSize());

        jDesktopPane_main.revalidate();
        jDesktopPane_main.repaint();
    }//GEN-LAST:event_jPanel_menu_4MouseClicked

    private void jPanel_menu_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_5MouseClicked
        try {
            jPanel_menu_1.setBackground(defaultColor);
            jPanel_menu_2.setBackground(defaultColor);
            jPanel_menu_3.setBackground(defaultColor);
            jPanel_menu_4.setBackground(defaultColor);
            jPanel_menu_5.setBackground(clickedColor);
            jLabel_menu_name.setText(jLabel_menu_5_text.getText());
            jLabel_user.setText(currentUser);
            jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-user-round-32.png")));
            jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-40.png")));

            Menu_5__QuanLy_Internal_GUI menu_5 = new Menu_5__QuanLy_Internal_GUI();
            jDesktopPane_main.removeAll();
            jDesktopPane_main.add(menu_5).setVisible(true);

            menu_5.setSize(jDesktopPane_main.getSize());

            jDesktopPane_main.revalidate();
            jDesktopPane_main.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel_menu_5MouseClicked

    //open menu 2
    private void jPanel_menu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_2MouseClicked
        jPanel_menu_1.setBackground(defaultColor);
        jPanel_menu_2.setBackground(clickedColor);
        jPanel_menu_3.setBackground(defaultColor);
        jPanel_menu_4.setBackground(defaultColor);
        jPanel_menu_5.setBackground(defaultColor);
        jLabel_menu_name.setIcon(null);
        jLabel_menu_name.setText("Mang đi");
        jLabel_user.setText(currentUser);
        jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-user-round-32.png")));
        jLabel_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-40.png")));

        Menu_2_TaiQuay_Internal_GUI menu_2 = new Menu_2_TaiQuay_Internal_GUI();
        jDesktopPane_main.removeAll();
        menu_2.jLabel_currentUS.setText(jLabel_user.getText());
        jDesktopPane_main.add(menu_2).setVisible(true);

        menu_2.setSize(jDesktopPane_main.getSize());

        jDesktopPane_main.revalidate();
        jDesktopPane_main.repaint();

        menu_2.updateBill();
    }//GEN-LAST:event_jPanel_menu_2MouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        int option = JOptionPane.showOptionDialog(this, "Bạn có muốn đăng xuất không?", "Log out",
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Có", "Không"},
                "Không");
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
            Login_GUI gUI = new Login_GUI();
            gUI.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard_GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dayLabel;
    public javax.swing.JDesktopPane jDesktopPane_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_menu_1_icon;
    private javax.swing.JLabel jLabel_menu_1_text;
    private javax.swing.JLabel jLabel_menu_2_icon;
    private javax.swing.JLabel jLabel_menu_2_text;
    private javax.swing.JLabel jLabel_menu_3_icon;
    private javax.swing.JLabel jLabel_menu_3_text;
    private javax.swing.JLabel jLabel_menu_4_icon;
    private javax.swing.JLabel jLabel_menu_4_text;
    private javax.swing.JLabel jLabel_menu_5_icon;
    private javax.swing.JLabel jLabel_menu_5_text;
    public javax.swing.JLabel jLabel_menu_name;
    private javax.swing.JLabel jLabel_nameShop;
    public javax.swing.JLabel jLabel_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_menu_1;
    private javax.swing.JPanel jPanel_menu_2;
    private javax.swing.JPanel jPanel_menu_3;
    private javax.swing.JPanel jPanel_menu_4;
    private javax.swing.JPanel jPanel_menu_5;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

}
