/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import connectDB.ConnectDB;
import dao.Ban_DAO;
import entity.Ban;
import entity.SanPham;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nvmin
 */
public class Menu_1_TaiBan_Internal_GUI extends javax.swing.JInternalFrame {

    Color defaultColorBg, clickedColorBg, defaultColorTxt, clickedColorTxt;
    private Ban_DAO ban_DAO;

    /**
     * Creates new form NewJInternalFrame_Menu_1
     */
    public Menu_1_TaiBan_Internal_GUI() {
        initComponents();

        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        ban_DAO = new Ban_DAO();
        //
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        // 
        defaultColorBg = new Color(255, 255, 255);
        clickedColorBg = new Color(0, 102, 51);
        defaultColorTxt = new Color(0, 0, 0);
        clickedColorTxt = new Color(255, 255, 255);

        displayTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void displayTables() {
        ArrayList<Ban> danhSachBan = ban_DAO.getAllTableBan();
        jPanel_table_Grid.removeAll();
        for (Ban ban : danhSachBan) {
            JPanel tablePanel = createTablePanel(ban);
            // Thêm sự kiện click cho mỗi JPanel sản phẩm
            tablePanel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    String code = ban.getMaBan();
                    String name = ban.getTenBan();
                    String status = ban.getTrangThaiBan();
                    int quantity = ban.getSoLuongNguoi();
                    
                    jDialog_table_empty.setLocationRelativeTo(null);
                    jDialog_table_empty.setSize(350, 350);
                    jDialog_table_active.setLocationRelativeTo(null);
                    jDialog_table_active.setSize(350, 350);
                    jDialog_table_reserve.setLocationRelativeTo(null);
                    jDialog_table_reserve.setSize(350, 350);
                    //empty
                    jLabel_code_empty.setText(code);
                    jLabel_name_empty.setText(name);
                    jLabel_detail_empty.setText(status + " - " + quantity + " người");
                    //active
                    jLabel_code_active.setText(code);
                    jLabel_name_active.setText(name);
                    jLabel_detail_active.setText(status + " - " + quantity + " người");
                    //reserve
                    jLabel_code_reserve.setText(code);
                    jLabel_name_reserve.setText(name);
                    jLabel_detail_reserve.setText(status + " - " + quantity + " người");
                    if (status.equals("Trống")) {
                        jDialog_table_empty.setVisible(true);
                    } else if (status.equals("Hoạt động")) {
                        jDialog_table_active.setVisible(true);
                    } else {
                        jDialog_table_reserve.setVisible(true);
                    }

                    jDialog_table_empty.setLocationRelativeTo(null);
                    jDialog_table_empty.setSize(300, 300);

                }
            });

            jPanel_table_Grid.add(tablePanel);
        }

        jPanel_table_Grid.revalidate();
        jPanel_table_Grid.repaint();
    }

    public JPanel createTablePanel(Ban ban) {
        JPanel tablePanel = new JPanel(new BorderLayout());
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // Ten <3
        JLabel codeLabel = new JLabel(ban.getMaBan());
        codeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        codeLabel.setFont(new Font("Arial", Font.BOLD, 15));
        JLabel nameLabel = new JLabel(ban.getTenBan());
        nameLabel.setHorizontalAlignment(SwingConstants.CENTER);
        nameLabel.setFont(new Font("Arial", Font.BOLD, 15));
        JLabel nvLabel = new JLabel();
        nvLabel.setHorizontalAlignment(SwingConstants.CENTER);
        nvLabel.setFont(new Font("Arial", Font.BOLD, 15));
        JPanel jPanel_heading = new JPanel(new GridLayout(1, 2));
        jPanel_heading.add(codeLabel);
        jPanel_heading.add(nvLabel);
        jPanel_heading.add(nameLabel);
        // Trang Thai <3
        JLabel statusLabel = new JLabel();
        statusLabel.setHorizontalAlignment(SwingConstants.CENTER);
        // So Luong <3
        JLabel quantityLabel = new JLabel(String.valueOf(ban.getTrangThaiBan() + " - " + ban.getSoLuongNguoi() + " người"));
        quantityLabel.setHorizontalAlignment(SwingConstants.CENTER);
        quantityLabel.setFont(new Font("Arial", Font.BOLD, 15));
        //
        tablePanel.add(jPanel_heading, BorderLayout.NORTH);
        tablePanel.add(statusLabel, BorderLayout.CENTER);
        tablePanel.add(quantityLabel, BorderLayout.SOUTH);

        tablePanel.setPreferredSize(new Dimension(tablePanel.getPreferredSize().width, 150));

        if (ban.getTrangThaiBan().equals("Trống")) {
            tablePanel.setBackground(Color.WHITE);
            jPanel_heading.setBackground(Color.WHITE);
            statusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/table-48.png")));
        } else if (ban.getTrangThaiBan().equals("Đặt trước")) {
            tablePanel.setBackground(Color.LIGHT_GRAY);
            jPanel_heading.setBackground(Color.LIGHT_GRAY);
            statusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock-48.png")));
        } else {
            tablePanel.setBackground(new Color(0, 102, 54));
            jPanel_heading.setBackground(new Color(0, 102, 54));
            codeLabel.setForeground(Color.WHITE);
            nameLabel.setForeground(Color.WHITE);
            statusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/users-round-48.png")));
            quantityLabel.setForeground(Color.WHITE);
        }
        //
        return tablePanel;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_table_empty = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel_in4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_name_empty = new javax.swing.JLabel();
        jLabel_detail_empty = new javax.swing.JLabel();
        jButton_reserve = new javax.swing.JButton();
        jButton_enter = new javax.swing.JButton();
        jLabel_code_empty = new javax.swing.JLabel();
        jDialog_table_active = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel_in7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel_name_active = new javax.swing.JLabel();
        jLabel_detail_active = new javax.swing.JLabel();
        jButton_changeEmptyTable_active = new javax.swing.JButton();
        jLabel_code_active = new javax.swing.JLabel();
        jDialog_table_reserve = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel_in8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel_name_reserve = new javax.swing.JLabel();
        jLabel_detail_reserve = new javax.swing.JLabel();
        jButton_changeEmptyTable_reserve = new javax.swing.JButton();
        jLabel_code_reserve = new javax.swing.JLabel();
        jPanel_container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel_table_Grid = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_currentUS = new javax.swing.JLabel();

        jDialog_table_empty.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_table_empty.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialog_table_empty.setModal(true);

        jPanel5.setBackground(new java.awt.Color(0, 102, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel_in4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_in4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_in4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_in4.setText("Thông tin đặt bàn");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jDialog_table_empty.getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_name_empty.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_name_empty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_name_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_detail_empty.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_detail_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_reserve.setBackground(new java.awt.Color(204, 204, 204));
        jButton_reserve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_reserve.setText("Đặt trước");
        jButton_reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reserveActionPerformed(evt);
            }
        });

        jButton_enter.setBackground(new java.awt.Color(0, 102, 51));
        jButton_enter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_enter.setForeground(new java.awt.Color(255, 255, 255));
        jButton_enter.setText("Vào bàn");
        jButton_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enterActionPerformed(evt);
            }
        });

        jLabel_code_empty.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel_code_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_code_empty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel_name_empty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_detail_empty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel_code_empty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_name_empty, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_detail_empty, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDialog_table_empty.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jDialog_table_active.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_table_active.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialog_table_active.setModal(true);

        jPanel11.setBackground(new java.awt.Color(0, 102, 51));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel_in7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_in7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_in7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_in7.setText("Thông tin đặt bàn");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in7, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jDialog_table_active.getContentPane().add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_name_active.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_name_active.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_name_active.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_detail_active.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_detail_active.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_changeEmptyTable_active.setBackground(new java.awt.Color(0, 102, 51));
        jButton_changeEmptyTable_active.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_changeEmptyTable_active.setForeground(new java.awt.Color(255, 255, 255));
        jButton_changeEmptyTable_active.setText("Khôi phục bàn trống");
        jButton_changeEmptyTable_active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeEmptyTable_activeActionPerformed(evt);
            }
        });

        jLabel_code_active.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel_code_active.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_code_active, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(jLabel_name_active, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_detail_active, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_changeEmptyTable_active, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel_code_active, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_name_active, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_detail_active, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton_changeEmptyTable_active, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog_table_active.getContentPane().add(jPanel12, java.awt.BorderLayout.CENTER);

        jDialog_table_reserve.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_table_reserve.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialog_table_reserve.setModal(true);

        jPanel13.setBackground(new java.awt.Color(0, 102, 51));
        jPanel13.setPreferredSize(new java.awt.Dimension(500, 80));

        jLabel_in8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_in8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_in8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_in8.setText("Thông tin đặt bàn");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in8, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_in8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jDialog_table_reserve.getContentPane().add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_name_reserve.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_name_reserve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_name_reserve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_detail_reserve.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_detail_reserve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_changeEmptyTable_reserve.setBackground(new java.awt.Color(204, 204, 204));
        jButton_changeEmptyTable_reserve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_changeEmptyTable_reserve.setText("Khôi phục bàn trống");
        jButton_changeEmptyTable_reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeEmptyTable_reserveActionPerformed(evt);
            }
        });

        jLabel_code_reserve.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel_code_reserve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_code_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(jLabel_name_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_detail_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_changeEmptyTable_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel_code_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_name_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_detail_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton_changeEmptyTable_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog_table_reserve.getContentPane().add(jPanel14, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(746, 559));

        jPanel_container.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_container.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_table_Grid.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_table_Grid.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel_table_Grid.setLayout(new java.awt.GridLayout(0, 4, 15, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanel_table_Grid.add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanel_table_Grid.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_table_Grid, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel_table_Grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 338, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        jPanel_container.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_container, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(896, 0));

        jLabel_currentUS.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jLabel_currentUS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_currentUS.setText("MA NHAN VIEN O DAY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_currentUS, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_currentUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enterActionPerformed
        String tableCode = jLabel_code_empty.getText();
        String tableName = jLabel_name_empty.getText();
        String trangThai = "Hoạt động";
        try {
            ban_DAO.updateStatus(trangThai, tableName);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_1_TaiBan_Internal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayTables();
        jDialog_table_empty.dispose();
        jPanel_container.removeAll();

        Dashboard_GUI dashboard_GUI = new Dashboard_GUI();
        Menu_2_TaiQuay_Internal_GUI menu_2 = new Menu_2_TaiQuay_Internal_GUI();
        
        menu_2.jLabel_currentUS.setText(jLabel_currentUS.getText());
        menu_2.jLabel_table_codes.setText(tableCode);
        menu_2.jLabel_table_name.setText(tableName);
        jPanel_container.add(menu_2).setVisible(true);
        
        jPanel_container.revalidate();
        jPanel_container.repaint();
        jDialog_table_empty.dispose();
        
    }//GEN-LAST:event_jButton_enterActionPerformed

    private void jButton_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reserveActionPerformed
        String tableName = jLabel_name_empty.getText();
        String trangThai = "Đặt trước";
        try {
            ban_DAO.updateStatus(trangThai, tableName);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_1_TaiBan_Internal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayTables();
        jDialog_table_empty.dispose();
    }//GEN-LAST:event_jButton_reserveActionPerformed

    private void jButton_changeEmptyTable_activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeEmptyTable_activeActionPerformed
        String tableName = jLabel_name_active.getText();
        String trangThai = "Trống";
        try {
            ban_DAO.updateStatus(trangThai, tableName);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_1_TaiBan_Internal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayTables();
        jDialog_table_active.dispose();
    }//GEN-LAST:event_jButton_changeEmptyTable_activeActionPerformed

    private void jButton_changeEmptyTable_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeEmptyTable_reserveActionPerformed
        String tableName = jLabel_name_reserve.getText();
        String trangThai = "Trống";
        try {
            ban_DAO.updateStatus(trangThai, tableName);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_1_TaiBan_Internal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayTables();
        jDialog_table_reserve.dispose();
    }//GEN-LAST:event_jButton_changeEmptyTable_reserveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_changeEmptyTable_active;
    private javax.swing.JButton jButton_changeEmptyTable_reserve;
    private javax.swing.JButton jButton_enter;
    private javax.swing.JButton jButton_reserve;
    private javax.swing.JDialog jDialog_table_active;
    private javax.swing.JDialog jDialog_table_empty;
    private javax.swing.JDialog jDialog_table_reserve;
    private javax.swing.JLabel jLabel_code_active;
    private javax.swing.JLabel jLabel_code_empty;
    private javax.swing.JLabel jLabel_code_reserve;
    public javax.swing.JLabel jLabel_currentUS;
    private javax.swing.JLabel jLabel_detail_active;
    private javax.swing.JLabel jLabel_detail_empty;
    private javax.swing.JLabel jLabel_detail_reserve;
    private javax.swing.JLabel jLabel_in4;
    private javax.swing.JLabel jLabel_in7;
    private javax.swing.JLabel jLabel_in8;
    private javax.swing.JLabel jLabel_name_active;
    private javax.swing.JLabel jLabel_name_empty;
    private javax.swing.JLabel jLabel_name_reserve;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JPanel jPanel_table_Grid;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
