/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import connectDB.ConnectDB;
import dao.KhachHang_DAO;
import entity.Ban;
import entity.KhachHang;
import entity.SanPham;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nvmin
 */
public class Menu_4_KhachHang_Internal_GUI extends javax.swing.JInternalFrame {

    private KhachHang_DAO khachHang_DAO;

    /**
     * Creates new form NewJInternalFrame_Menu_4
     */
    public Menu_4_KhachHang_Internal_GUI() {
        initComponents();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        khachHang_DAO = new KhachHang_DAO();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        for (int i = 0; i < jTable_customer.getColumnCount(); i++) {
            this.jTable_customer.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRenderer() {
                {
                    setHorizontalAlignment(SwingConstants.CENTER);
                }
            });
        }

        jInternalFrame_editCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI uiEdit = (BasicInternalFrameUI) jInternalFrame_editCustomer.getUI();
        uiEdit.setNorthPane(null);

        displayListCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void displayListCustomer() {
        DefaultTableModel model = (DefaultTableModel) jTable_customer.getModel();
        ArrayList<KhachHang> danhSachKH = khachHang_DAO.getAllTableKhachHang();
        for (KhachHang khachHang : danhSachKH) {
            model.addRow(new Object[]{khachHang.getMaKH(), khachHang.getTenKH(), khachHang.getSoDienThoaiKH(), khachHang.isGioiTinhKH() ? "Nam" : "Nữ", khachHang.getDiaChiKH()});
        }

        //render
        for (int i = 0; i < jTable_customer.getColumnCount(); i++) {
            this.jTable_customer.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRenderer() {
                {
                    setHorizontalAlignment(SwingConstants.CENTER);
                }
            });
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame_editCustomer = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel_name_title = new javax.swing.JLabel();
        jLabel_phone_title = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jLabel1_editName = new javax.swing.JLabel();
        jLabel1_editPhone = new javax.swing.JLabel();
        jLabel_editGender = new javax.swing.JLabel();
        jLabel1_editAddress = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_maKH = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_search = new javax.swing.JButton();
        jButton_addNew = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_customer = new javax.swing.JTable();
        jDesktopPane_information = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame_editCustomer.setBackground(new java.awt.Color(204, 204, 255));
        jInternalFrame_editCustomer.setMinimumSize(new java.awt.Dimension(100, 200));
        jInternalFrame_editCustomer.setPreferredSize(new java.awt.Dimension(600, 764));
        jInternalFrame_editCustomer.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(588, 120));

        jLabel_name_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel_name_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_name_title.setText("Họ tên");

        jLabel_phone_title.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel_phone_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_phone_title.setText("0353999798");

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 51)));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thông tin khách hàng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_name_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_phone_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel_name_title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_phone_title, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        jInternalFrame_editCustomer.getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Họ tên");

        jTextField_name.setEditable(false);
        jTextField_name.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_name.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jTextField_phone.setEditable(false);
        jTextField_phone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_phone.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Giới tính");

        jRadioButton_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_male);
        jRadioButton_male.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButton_male.setText("Nam");
        jRadioButton_male.setEnabled(false);

        jRadioButton_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_female);
        jRadioButton_female.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButton_female.setText("Nữ");
        jRadioButton_female.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Địa chỉ");

        jTextField_address.setEditable(false);
        jTextField_address.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_address.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel1_editName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_editName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-right-24.png"))); // NOI18N
        jLabel1_editName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_editNameMouseClicked(evt);
            }
        });

        jLabel1_editPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_editPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-right-24.png"))); // NOI18N
        jLabel1_editPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_editPhoneMouseClicked(evt);
            }
        });

        jLabel_editGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_editGender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-right-24.png"))); // NOI18N
        jLabel_editGender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_editGenderMouseClicked(evt);
            }
        });

        jLabel1_editAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_editAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-right-24.png"))); // NOI18N
        jLabel1_editAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_editAddressMouseClicked(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(0, 102, 51));
        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Thêm");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(204, 51, 0));
        jButton_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("Xoá");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_save.setBackground(new java.awt.Color(204, 204, 0));
        jButton_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setText("Lưu");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Mã khách hàng");

        jTextField_maKH.setEditable(false);
        jTextField_maKH.setBackground(new java.awt.Color(255, 255, 254));
        jTextField_maKH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField_maKH.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_maKH.setBorder(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1_editPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_editGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1_editAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1_editName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1_editPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel_editGender, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1_editName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1_editAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jInternalFrame_editCustomer.getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel_container.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));

        jButton_search.setBackground(new java.awt.Color(0, 102, 51));
        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refesh-36.png"))); // NOI18N
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jButton_addNew.setBackground(new java.awt.Color(0, 102, 51));
        jButton_addNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-plus.png"))); // NOI18N
        jButton_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton_addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton_addNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jTable_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ tên", "Số điện thoại", "Giới tính", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_customer.setName(""); // NOI18N
        jTable_customer.setRowHeight(40);
        jTable_customer.setSelectionBackground(new java.awt.Color(0, 102, 51));
        jTable_customer.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable_customer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_customer.setShowGrid(false);
        jTable_customer.getTableHeader().setReorderingAllowed(false);
        jTable_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_customerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_customer);
        if (jTable_customer.getColumnModel().getColumnCount() > 0) {
            jTable_customer.getColumnModel().getColumn(0).setResizable(false);
            jTable_customer.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable_customer.getColumnModel().getColumn(1).setResizable(false);
            jTable_customer.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable_customer.getColumnModel().getColumn(2).setResizable(false);
            jTable_customer.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable_customer.getColumnModel().getColumn(3).setResizable(false);
            jTable_customer.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable_customer.getColumnModel().getColumn(4).setResizable(false);
            jTable_customer.getColumnModel().getColumn(4).setPreferredWidth(200);
        }
        jTable_customer.getAccessibleContext().setAccessibleName("");
        jTable_customer.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_container.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_container, java.awt.BorderLayout.CENTER);

        jDesktopPane_information.setPreferredSize(new java.awt.Dimension(600, 502));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-round-x-48.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chọn để xem thông tin chi tiết");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jDesktopPane_information.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane_informationLayout = new javax.swing.GroupLayout(jDesktopPane_information);
        jDesktopPane_information.setLayout(jDesktopPane_informationLayout);
        jDesktopPane_informationLayout.setHorizontalGroup(
            jDesktopPane_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane_informationLayout.setVerticalGroup(
            jDesktopPane_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane_information, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_customerMouseClicked
        jDesktopPane_information.removeAll();
        jDesktopPane_information.revalidate();
        jDesktopPane_information.repaint();

        jDesktopPane_information.add(jInternalFrame_editCustomer).setVisible(true);
        jInternalFrame_editCustomer.setSize(jDesktopPane_information.getSize());

        int rowIndex = this.jTable_customer.getSelectedRow();
        String ma = this.jTable_customer.getValueAt(rowIndex, 0).toString();
        String name = this.jTable_customer.getValueAt(rowIndex, 1).toString();
        String phone = this.jTable_customer.getValueAt(rowIndex, 2).toString();
        String gender = this.jTable_customer.getValueAt(rowIndex, 3).toString();
        String address = this.jTable_customer.getValueAt(rowIndex, 4).toString();

        jLabel_name_title.setText(name);
        jLabel_phone_title.setText(phone);
        jTextField_maKH.setText(ma);
        jTextField_name.setText(name);
        jTextField_phone.setText(phone);
        if (gender.equals("Nam")) {
            jRadioButton_male.setSelected(true);
            jRadioButton_female.setSelected(false);
        } else {
            jRadioButton_male.setSelected(false);
            jRadioButton_female.setSelected(true);
        }
        jTextField_address.setText(address);
        //
        jButton_delete.setEnabled(true);
        jButton_delete.setBackground(new Color(204, 51, 0));
        jButton_save.setEnabled(true);
        jButton_save.setBackground(Color.YELLOW);
    }//GEN-LAST:event_jTable_customerMouseClicked

    private void jLabel1_editNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_editNameMouseClicked
        if (!jTextField_name.isEditable()) {
            jTextField_name.setEditable(true);
        } else {
            jTextField_name.setEditable(false);
        }
    }//GEN-LAST:event_jLabel1_editNameMouseClicked

    private void jLabel_editGenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editGenderMouseClicked
        if (!(jRadioButton_male.isEnabled() && jRadioButton_female.isEnabled())) {
            jRadioButton_male.setEnabled(true);
            jRadioButton_female.setEnabled(true);
        } else {
            jRadioButton_male.setEnabled(false);
            jRadioButton_female.setEnabled(false);
        }
    }//GEN-LAST:event_jLabel_editGenderMouseClicked

    private void jLabel1_editAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_editAddressMouseClicked
        if (!jTextField_address.isEditable()) {
            jTextField_address.setEditable(true);
        } else {
            jTextField_address.setEditable(false);
        }
    }//GEN-LAST:event_jLabel1_editAddressMouseClicked

    private void jLabel1_editPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_editPhoneMouseClicked
        if (!jTextField_phone.isEditable()) {
            jTextField_phone.setEditable(true);
        } else {
            jTextField_phone.setEditable(false);
        }
    }//GEN-LAST:event_jLabel1_editPhoneMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        Menu_4_KhachHang_Dialog_GUI customer = new Menu_4_KhachHang_Dialog_GUI((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        customer.setVisible(true);
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        //dbs
        String maKH = jTextField_maKH.getText().toString();
        String tenKH = jTextField_name.getText().trim();
        try {
            khachHang_DAO.deleteCustomer(maKH);
            JOptionPane.showMessageDialog(this, "Đã xoá " + tenKH + " ra danh mục khách hàng", "Success", JOptionPane.WARNING_MESSAGE);
            jTextField_maKH.setText("");
            jTextField_name.setText("");
            jTextField_phone.setText("");
            jRadioButton_male.setSelected(true);
            jRadioButton_female.setSelected(false);
            jTextField_address.setText("");
            jButton_delete.setEnabled(false);
            jButton_save.setEnabled(false);
            jButton_delete.setBackground(Color.LIGHT_GRAY);
            jButton_save.setBackground(Color.LIGHT_GRAY);
        } catch (Exception e2) {
            JOptionPane.showMessageDialog(this, "Xoá khách hàng không thành công!", "Fail", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        DocDuLieuDatabaseVaoTable();
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addNewActionPerformed
        Menu_4_KhachHang_Dialog_GUI customer = new Menu_4_KhachHang_Dialog_GUI((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        customer.setVisible(true);
    }//GEN-LAST:event_jButton_addNewActionPerformed

    public void DocDuLieuDatabaseVaoTable() {
        List<KhachHang> list = khachHang_DAO.getAllTableKhachHang();
        DefaultTableModel model = (DefaultTableModel) jTable_customer.getModel();
        model.setRowCount(0);
        for (KhachHang kh : list) {
            model.addRow(new Object[]{kh.getMaKH(), kh.getTenKH(),
                kh.getSoDienThoaiKH(), kh.isGioiTinhKH()?"Nam":"Nữ", kh.getDiaChiKH()});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_addNew;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_search;
    private javax.swing.JDesktopPane jDesktopPane_information;
    private javax.swing.JInternalFrame jInternalFrame_editCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_editAddress;
    private javax.swing.JLabel jLabel1_editName;
    private javax.swing.JLabel jLabel1_editPhone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_editGender;
    private javax.swing.JLabel jLabel_name_title;
    private javax.swing.JLabel jLabel_phone_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_customer;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_maKH;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phone;
    // End of variables declaration//GEN-END:variables
}
