/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author nvmin
 */
public class Menu_2_ThanhToan_Dialog_GUI extends javax.swing.JDialog {

    Locale localeVN = new Locale("vi", "VN");
    NumberFormat numf = NumberFormat.getCurrencyInstance(localeVN);
    Color defaultColor, clickedColor;
    //format
    DecimalFormat decimalFormat = new DecimalFormat("#,##0");
    JFormattedTextField jFormattedTextField = new JFormattedTextField(decimalFormat);

    JTextField focusedTextField = null;
    JTextField lostTextField = null;

    /**
     * Creates new form Payment_GUI
     */
    public Menu_2_ThanhToan_Dialog_GUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        defaultColor = new Color(0, 102, 51);
        clickedColor = new Color(0, 54, 27);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        setBounds(0, 0, screenSize.width, screenSize.height);

        getRootPane().registerKeyboardAction(e -> dispose(), KeyStroke.getKeyStroke("ESCAPE"), JComponent.WHEN_IN_FOCUSED_WINDOW);

        Component[] components = jPanel_keyBoard.getComponents();
        for (Component component : components) {
            if (component instanceof JButton jButton) {
                jButton.addActionListener(buttonListener);
            }
        }

//        jTextField_surcharge.addFocusListener(textFieldFocusListener);
        jTextField_cashValue.addFocusListener(textFieldFocusListener);

    }

    ActionListener buttonListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton clickedButton = (JButton) e.getSource();
            String buttonText = clickedButton.getText();
            if (buttonText.equals("Nhập lại")) {
                focusedTextField.setText("0");
            } else if (buttonText.equals("Hoàn tất")) {
                return;
            } else {
                if (focusedTextField != null) {
                    String currentText = focusedTextField.getText().replace(",", "");
                    try {
                        int buttonInt = Integer.parseInt(buttonText);
                        long newValue = Long.parseLong(currentText + buttonInt);
                        if (focusedTextField.equals(jTextField_cashValue)) {
                            focusedTextField.setText(decimalFormat.format(newValue));
                        } else {
                            if (newValue <= 100) {
                                focusedTextField.setText(decimalFormat.format(newValue));
                            } else {
                                focusedTextField.setText("0");
                            }
                        }
                    } catch (NumberFormatException ex) {

                    }
                }
            }
        }
    };

    FocusListener textFieldFocusListener = new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            focusedTextField = (JTextField) e.getSource();

        }

        @Override
        public void focusLost(FocusEvent e) {
            lostTextField = (JTextField) e.getSource();
            String text = lostTextField.getText().replaceAll(",", ""); // Remove commas for parsing
            if (text.isEmpty()) {
                lostTextField.setText("0");
            } else {
                try {
                    double value = Double.parseDouble(text);
                    String formattedValue = decimalFormat.format(value);
                    lostTextField.setText(formattedValue);
                } catch (NumberFormatException ex) {

                }
            }
        }

    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_surcharge = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel_note = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jTextField_note_bill = new javax.swing.JTextField();
        jPanel_payMethods = new javax.swing.JPanel();
        jPanel_cash = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel_cash = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel_methodsTxt = new javax.swing.JLabel();
        jTextField_cashValue = new javax.swing.JTextField();
        jPanel_donVi = new javax.swing.JPanel();
        jLabel_donVi = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_temporary = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel_money = new javax.swing.JPanel();
        jButton_20k = new javax.swing.JButton();
        jButton_50k = new javax.swing.JButton();
        jButton_100k = new javax.swing.JButton();
        jButton_200k = new javax.swing.JButton();
        jButton_500k = new javax.swing.JButton();
        jPanel_voucher = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel_refund = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel_keyBoard = new javax.swing.JPanel();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_retype = new javax.swing.JButton();
        jButton_bill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1021, 80));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-36.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Thanh Toán");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tạm tính");
        jLabel4.setPreferredSize(new java.awt.Dimension(59, 21));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Giảm giá");

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("%");

        jTextField_surcharge.setEditable(false);
        jTextField_surcharge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField_surcharge.setText("0");
        jTextField_surcharge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField_surcharge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_surchargeFocusLost(evt);
            }
        });
        jTextField_surcharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_surchargeMouseClicked(evt);
            }
        });
        jTextField_surcharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_surchargeActionPerformed(evt);
            }
        });
        jTextField_surcharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_surchargeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addComponent(jTextField_surcharge, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField_surcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField6.setText("0");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel17.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 80));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel24);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_note.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("Ghi chú hoá đơn");

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_note_bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_note_bill.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField_note_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_note_billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField_note_bill, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField_note_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_payMethods.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_cash.setBackground(new java.awt.Color(0, 51, 27));
        jPanel_cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_cashMouseClicked(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dolar-20.png"))); // NOI18N

        jLabel_cash.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_cash.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cash.setText("Tiền mặt");

        javax.swing.GroupLayout jPanel_cashLayout = new javax.swing.GroupLayout(jPanel_cash);
        jPanel_cash.setLayout(jPanel_cashLayout);
        jPanel_cashLayout.setHorizontalGroup(
            jPanel_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_cash, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel_cashLayout.setVerticalGroup(
            jPanel_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cashLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_cash, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_payMethodsLayout = new javax.swing.GroupLayout(jPanel_payMethods);
        jPanel_payMethods.setLayout(jPanel_payMethodsLayout);
        jPanel_payMethodsLayout.setHorizontalGroup(
            jPanel_payMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_payMethodsLayout.createSequentialGroup()
                .addComponent(jPanel_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_payMethodsLayout.setVerticalGroup(
            jPanel_payMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_payMethodsLayout.createSequentialGroup()
                .addComponent(jPanel_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_methodsTxt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_methodsTxt.setText("Nhập số tiền khách đưa");

        jTextField_cashValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField_cashValue.setForeground(new java.awt.Color(204, 51, 0));
        jTextField_cashValue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_cashValue.setText("0");
        jTextField_cashValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField_cashValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_cashValueFocusLost(evt);
            }
        });
        jTextField_cashValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cashValueMouseClicked(evt);
            }
        });
        jTextField_cashValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cashValueActionPerformed(evt);
            }
        });
        jTextField_cashValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_cashValueKeyTyped(evt);
            }
        });

        jPanel_donVi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_donVi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_donVi.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_donVi.setText("đ");

        javax.swing.GroupLayout jPanel_donViLayout = new javax.swing.GroupLayout(jPanel_donVi);
        jPanel_donVi.setLayout(jPanel_donViLayout);
        jPanel_donViLayout.setHorizontalGroup(
            jPanel_donViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_donViLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_donVi, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel_donViLayout.setVerticalGroup(
            jPanel_donViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_donVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_methodsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_cashValue, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_donVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_methodsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jTextField_cashValue, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addComponent(jPanel_donVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel30.setBackground(new java.awt.Color(0, 102, 51));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tổng tiền");

        jLabel_temporary.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_temporary.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_temporary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_temporary, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
            .addComponent(jLabel_temporary, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_noteLayout = new javax.swing.GroupLayout(jPanel_note);
        jPanel_note.setLayout(jPanel_noteLayout);
        jPanel_noteLayout.setHorizontalGroup(
            jPanel_noteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_noteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_noteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_payMethods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_noteLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_noteLayout.setVerticalGroup(
            jPanel_noteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_noteLayout.createSequentialGroup()
                .addGroup(jPanel_noteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel_payMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
            .addComponent(jPanel_note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jPanel_money.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_money.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel_money.setLayout(new java.awt.GridLayout(1, 5, 20, 20));

        jButton_20k.setBackground(new java.awt.Color(255, 255, 254));
        jButton_20k.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_20k.setText("20,000đ");
        jButton_20k.setPreferredSize(new java.awt.Dimension(60, 80));
        jButton_20k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_20kActionPerformed(evt);
            }
        });
        jPanel_money.add(jButton_20k);

        jButton_50k.setBackground(new java.awt.Color(255, 255, 254));
        jButton_50k.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_50k.setText("50,000đ");
        jButton_50k.setPreferredSize(new java.awt.Dimension(60, 80));
        jButton_50k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_50kActionPerformed(evt);
            }
        });
        jPanel_money.add(jButton_50k);

        jButton_100k.setBackground(new java.awt.Color(255, 255, 254));
        jButton_100k.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_100k.setText("100,000đ");
        jButton_100k.setPreferredSize(new java.awt.Dimension(60, 80));
        jButton_100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_100kActionPerformed(evt);
            }
        });
        jPanel_money.add(jButton_100k);

        jButton_200k.setBackground(new java.awt.Color(255, 255, 254));
        jButton_200k.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_200k.setText("200,000đ");
        jButton_200k.setPreferredSize(new java.awt.Dimension(60, 80));
        jButton_200k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_200kActionPerformed(evt);
            }
        });
        jPanel_money.add(jButton_200k);

        jButton_500k.setBackground(new java.awt.Color(255, 255, 254));
        jButton_500k.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_500k.setText("500,000đ");
        jButton_500k.setPreferredSize(new java.awt.Dimension(60, 80));
        jButton_500k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_500kActionPerformed(evt);
            }
        });
        jPanel_money.add(jButton_500k);

        jPanel_voucher.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_voucherLayout = new javax.swing.GroupLayout(jPanel_voucher);
        jPanel_voucher.setLayout(jPanel_voucherLayout);
        jPanel_voucherLayout.setHorizontalGroup(
            jPanel_voucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jPanel_voucherLayout.setVerticalGroup(
            jPanel_voucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tình tiền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_refund.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Trả lại tiền cho khách");

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(204, 0, 51));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_refundLayout = new javax.swing.GroupLayout(jPanel_refund);
        jPanel_refund.setLayout(jPanel_refundLayout);
        jPanel_refundLayout.setHorizontalGroup(
            jPanel_refundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_refundLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextField11))
        );
        jPanel_refundLayout.setVerticalGroup(
            jPanel_refundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel_keyBoard.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_keyBoard.setLayout(new java.awt.GridLayout(4, 3, 15, 15));

        jButton_1.setBackground(new java.awt.Color(255, 255, 254));
        jButton_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_1.setText("1");
        jPanel_keyBoard.add(jButton_1);

        jButton_2.setBackground(new java.awt.Color(255, 255, 254));
        jButton_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_2.setText("2");
        jPanel_keyBoard.add(jButton_2);

        jButton_3.setBackground(new java.awt.Color(255, 255, 254));
        jButton_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_3.setText("3");
        jPanel_keyBoard.add(jButton_3);

        jButton_4.setBackground(new java.awt.Color(255, 255, 254));
        jButton_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_4.setText("4");
        jPanel_keyBoard.add(jButton_4);

        jButton_5.setBackground(new java.awt.Color(255, 255, 254));
        jButton_5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_5.setText("5");
        jPanel_keyBoard.add(jButton_5);

        jButton_6.setBackground(new java.awt.Color(255, 255, 254));
        jButton_6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_6.setText("6");
        jPanel_keyBoard.add(jButton_6);

        jButton_7.setBackground(new java.awt.Color(255, 255, 254));
        jButton_7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_7.setText("7");
        jPanel_keyBoard.add(jButton_7);

        jButton_8.setBackground(new java.awt.Color(255, 255, 254));
        jButton_8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_8.setText("8");
        jPanel_keyBoard.add(jButton_8);

        jButton_9.setBackground(new java.awt.Color(255, 255, 254));
        jButton_9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_9.setText("9");
        jPanel_keyBoard.add(jButton_9);

        jButton_0.setBackground(new java.awt.Color(255, 255, 254));
        jButton_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_0.setText("0");
        jPanel_keyBoard.add(jButton_0);

        jButton_retype.setBackground(new java.awt.Color(204, 0, 0));
        jButton_retype.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_retype.setForeground(new java.awt.Color(255, 255, 255));
        jButton_retype.setText("Nhập lại");
        jPanel_keyBoard.add(jButton_retype);

        jButton_bill.setBackground(new java.awt.Color(0, 102, 51));
        jButton_bill.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_bill.setForeground(new java.awt.Color(255, 255, 255));
        jButton_bill.setText("Hoàn tất");
        jButton_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_billActionPerformed(evt);
            }
        });
        jPanel_keyBoard.add(jButton_bill);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_voucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_refund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_keyBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_refund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_keyBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_note_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_note_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_note_billActionPerformed

    private void jTextField_cashValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cashValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cashValueActionPerformed

    private void jPanel_cashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_cashMouseClicked
        jPanel_cash.setBackground(clickedColor);
//        jPanel_banking.setBackground(defaultColor);
        jLabel_methodsTxt.setText("Nhập số tiền khách đưa");
        jButton_20k.setEnabled(true);
        jButton_50k.setEnabled(true);
        jButton_100k.setEnabled(true);
        jButton_200k.setEnabled(true);
        jButton_500k.setEnabled(true);
        jTextField_cashValue.setEditable(true);
        jTextField_cashValue.requestFocus();
        jTextField_cashValue.selectAll();
        jTextField_cashValue.setVisible(true);
        jLabel_donVi.setVisible(true);
    }//GEN-LAST:event_jPanel_cashMouseClicked

    private void jTextField_cashValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cashValueMouseClicked
        jTextField_cashValue.selectAll();
    }//GEN-LAST:event_jTextField_cashValueMouseClicked

    private void jTextField_cashValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cashValueKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_cashValueKeyTyped

    private void jTextField_cashValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_cashValueFocusLost
        if (jTextField_cashValue.getText().isEmpty()) {
            jTextField_cashValue.setText("0");
        }
        try {
            double value = Double.parseDouble(jTextField_cashValue.getText());
            String formattedValue = decimalFormat.format(value);
            jTextField_cashValue.setText(formattedValue);
        } catch (NumberFormatException ex) {
            jTextField_cashValue.setText("0");
        }
    }//GEN-LAST:event_jTextField_cashValueFocusLost

    public void insertValToBill() {

    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField_surchargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_surchargeKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_surchargeKeyTyped

    private void jTextField_surchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_surchargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_surchargeActionPerformed

    private void jTextField_surchargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_surchargeMouseClicked
        jTextField_surcharge.setText("");
    }//GEN-LAST:event_jTextField_surchargeMouseClicked

    private void jTextField_surchargeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_surchargeFocusLost
        if (jTextField_surcharge.getText().isEmpty()) {
            jTextField_surcharge.setText("0");
        } else {
            double valueTxt = Double.parseDouble(jTextField_surcharge.getText());
            if (valueTxt > 100.0) {
                jTextField_surcharge.setText("0");
            }
        }
    }//GEN-LAST:event_jTextField_surchargeFocusLost

    private void jButton_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_billActionPerformed
        JOptionPane.showMessageDialog(this, "Đã thanh toán thành công, Quay lại menu để tiếp tục!", "Success", JOptionPane.PLAIN_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButton_billActionPerformed

    private void jButton_500kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_500kActionPerformed
        jTextField_cashValue.setText(jButton_500k.getText().replace("đ", ""));
    }//GEN-LAST:event_jButton_500kActionPerformed

    private void jButton_200kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_200kActionPerformed
        jTextField_cashValue.setText(jButton_200k.getText().replace("đ", ""));
    }//GEN-LAST:event_jButton_200kActionPerformed

    private void jButton_100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_100kActionPerformed
        jTextField_cashValue.setText(jButton_100k.getText().replace("đ", ""));
    }//GEN-LAST:event_jButton_100kActionPerformed

    private void jButton_50kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_50kActionPerformed
        jTextField_cashValue.setText(jButton_50k.getText().replace("đ", ""));
    }//GEN-LAST:event_jButton_50kActionPerformed

    private void jButton_20kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_20kActionPerformed
        jTextField_cashValue.setText(jButton_20k.getText().replace("đ", ""));
    }//GEN-LAST:event_jButton_20kActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double total = Double.parseDouble(jLabel_temporary.getText().replace(".0", ""));
        double cash = Double.parseDouble(jTextField_cashValue.getText().replace(",", ""));
        if (cash > total) {
            Locale localeVN = new Locale("vi", "VN");
            NumberFormat numf = NumberFormat.getCurrencyInstance(localeVN);
            jTextField11.setText(numf.format(cash - total));
        } else {
            jTextField11.setText("Khách đưa thiếu tiền");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_100k;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_200k;
    private javax.swing.JButton jButton_20k;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_500k;
    private javax.swing.JButton jButton_50k;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_bill;
    private javax.swing.JButton jButton_retype;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_cash;
    private javax.swing.JLabel jLabel_donVi;
    private javax.swing.JLabel jLabel_methodsTxt;
    public javax.swing.JLabel jLabel_temporary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_cash;
    private javax.swing.JPanel jPanel_donVi;
    private javax.swing.JPanel jPanel_keyBoard;
    private javax.swing.JPanel jPanel_money;
    private javax.swing.JPanel jPanel_note;
    private javax.swing.JPanel jPanel_payMethods;
    private javax.swing.JPanel jPanel_refund;
    private javax.swing.JPanel jPanel_voucher;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField_cashValue;
    private javax.swing.JTextField jTextField_note_bill;
    private javax.swing.JTextField jTextField_surcharge;
    // End of variables declaration//GEN-END:variables
}
